#!/bin/sh
# Check if the file exists
if [ -f /usr/share/applications/eddy.desktop ]; then
    # Revert to the original value
    sed -i 's/Exec=pkexec eddy-handler %U/Exec=eddy %U/g' /usr/share/applications/eddy.desktop
fi
