#!/bin/bash

export TEXTDOMAIN="eddy-handler"

# If the file does not exist or is older than a day, we start the update
if [ ! -e /var/cache/apt/pkgcache.bin ] || (( $(date +%s) - $(stat -c %Y /var/cache/apt/pkgcache.bin) >= 24*60*60 )); then
    # We update the database and display progress in a yad window with the system-software-update icon
    apt-get update 2>&1 | while read line; do
        echo "# $line"
        sleep 0.1
    done | yad --progress --title="$(gettext "Update")" --text="$(gettext "Updating the database...")" --pulsate --auto-close --center --no-buttons --window-icon=system-software-update

    # If yad was closed, we abort the script
    if [ $? -eq 252 ]; then
        yad --error --title="$(gettext "Error")" --text="$(gettext "Update was aborted")" --center --button=gtk-ok:0 --window-icon=error
        exit 1
    fi
fi

# We launch eddy
eddy $@
